Short inspection in train and validation datasets

In [7]:
import pandas as pd

# File paths
train_path = '../../data/splitted_datasets/allele/beta/train.tsv'
valid_path = '../../data/splitted_datasets/allele/beta/validation.tsv'

# Load the TSV files
train_df = pd.read_csv(train_path, sep='\t')
valid_df = pd.read_csv(valid_path, sep='\t')

# Print the head (first few rows) and length (number of rows) of both datasets
print("Train dataset head:")
print(train_df.head())  # First few rows of the training set
print(f"Train dataset length: {len(train_df)}")

print("\nValidation dataset head:")
print(valid_df.head())  # First few rows of the validation set
print(f"Validation dataset length: {len(valid_df)}")


/tmp/ipykernel_30452/2935229279.py:8: DtypeWarning: Columns (1,5) have mixed types. Specify dtype option on import or set low_memory=False.
  train_df = pd.read_csv(train_path, sep='\t')


Train dataset head:
   TCR_name\tTRAV\tTRAJ\tTRA_CDR3\tTRBV\tTRBJ\tTRB_CDR3\tTRB_leader\tTRAC\tTRBC\tLinker\tLink_order\tTRA_5_prime_seq\tTRA_3_prime_seq\tTRB_5_prime_seq\tTRB_3_prime_seq\tEpitope\tMHC\tMHC class  \
0                                                NaN                                                                                                                                               
1                                                NaN                                                                                                                                               
2                                                NaN                                                                                                                                               
3                                                NaN                                                                                                                                               


Investigations on ProtBERT-Embeddings in oder to get shape, type, etc., and be able to use them in the transformer

Paired

In [5]:
import numpy as np

# Path to the embeddings file
paired_all_epi_path = '../../data/embeddings/paired/allele/Epitope_paired_embeddings.npz'
paired_all_tra_path = '../../data/embeddings/paired/allele/TRA_paired_embeddings.npz'
paired_all_trb_path = '../../data/embeddings/paired/allele/TRB_paired_embeddings.npz'

beta_all_epi_path = '../../data/embeddings/beta/allele/Epitope_beta_embeddings.npz'
beta_all_trb_path = '../../data/embeddings/beta/allele/TRB_beta_embeddings.npz'
paths = [paired_all_epi_path, paired_all_tra_path,paired_all_trb_path ]

paths_beta = [beta_all_epi_path, beta_all_trb_path]
for path in paths_beta:
    # Load the NPZ file
    data = np.load(path)

    # Print available keys in the file
    print("Number of keys in the NPZ file:", len(data.files))

    # Inspect the shape and size of each stored array
    for key in data.files[:10]:
        array = data[key]
        print(f"\nKey: {key}")
        print(f"Shape: {array.shape}")
        print(f"Size: {array.size}")
        print(f"Data Type: {array.dtype}")
        print(f"Sample Data (first 5 elements):\n{array[:5] if array.ndim == 1 else array[:5, :5]}")


Number of keys in the NPZ file: 1896

Key: NLTTRTQL
Shape: (8, 1024)
Size: 8192
Data Type: float32
Sample Data (first 5 elements):
[[ 0.13486663  0.16832928  0.01105008 -0.2017876   0.21350099]
 [ 0.06380487  0.13675283  0.00786234 -0.12408309  0.31762993]
 [ 0.01229951  0.05960181  0.00698517 -0.0671403   0.08832411]
 [ 0.03610628  0.0980993   0.03087564 -0.11637626  0.03888167]
 [ 0.04467435  0.12075185  0.01568509 -0.10579667  0.06191917]]

Key: FIYIFHTL
Shape: (8, 1024)
Size: 8192
Data Type: float32
Sample Data (first 5 elements):
[[ 0.10352622  0.19366597  0.01785575 -0.14839908  0.25590894]
 [-0.05904485  0.1726287   0.08648816  0.00153423  0.19045785]
 [-0.03943206  0.14551184  0.07295718  0.01637407  0.07709593]
 [-0.04497753  0.11167102 -0.02338432  0.08326313  0.1050052 ]
 [-0.02016015  0.17720129  0.05871242  0.01146071  0.08313055]]

Key: YMHHMELPT
Shape: (9, 1024)
Size: 9216
Data Type: float32
Sample Data (first 5 elements):
[[ 0.06514921  0.11687686  0.04630813 -0.1331488

In [4]:
import numpy as np

# Path to the embeddings file
paired_all_epi_path = '../../data/embeddings/paired/allele/Epitope_paired_embeddings.npz'
paired_all_tra_path = '../../data/embeddings/paired/allele/TRA_paired_embeddings.npz'
paired_all_trb_path = '../../data/embeddings/paired/allele/TRB_paired_embeddings.npz'
paths = [paired_all_epi_path, paired_all_tra_path,paired_all_trb_path ]
for path in paths:
    # Load the NPZ file
    data = np.load(path)

    # Print available keys in the file
    print("Number of keys in the NPZ file:", len(data.files))

    # Inspect the shape and size of each stored array
    # for key in data.files[:10]:
    #     array = data[key]
    #     print(f"\nKey: {key}")
    #     print(f"Shape: {array.shape}")
    #     print(f"Size: {array.size}")
    #     print(f"Data Type: {array.dtype}")
    #     print(f"Sample Data (first 5 elements):\n{array[:5] if array.ndim == 1 else array[:5, :5]}")


Number of keys in the NPZ file: 1383
Number of keys in the NPZ file: 41519
Number of keys in the NPZ file: 45261


In [ ]:
# raising error, because length tra != length trb.  To be solved.

import numpy as np
import torch
from torch.nn.utils.rnn import pad_sequence

# Paths to the embeddings files
paired_all_epi_path = '../../data/embeddings/paired/allele/Epitope_paired_embeddings.npz'
paired_all_tra_path = '../../data/embeddings/paired/allele/TRA_paired_embeddings.npz'
paired_all_trb_path = '../../data/embeddings/paired/allele/TRB_paired_embeddings.npz'

# Load NPZ files
epi_data = np.load(paired_all_epi_path, allow_pickle=True)
tra_data = np.load(paired_all_tra_path, allow_pickle=True)
trb_data = np.load(paired_all_trb_path, allow_pickle=True)

# Extract embeddings
epi_embeddings = [torch.tensor(epi_data[key]) for key in epi_data]
tra_embeddings = [torch.tensor(tra_data[key]) for key in tra_data]
trb_embeddings = [torch.tensor(trb_data[key]) for key in trb_data]

# Find max sequence length
max_len = max(max(e.shape[0] for e in epi_embeddings), 
              max(e.shape[0] for e in tra_embeddings), 
              max(e.shape[0] for e in trb_embeddings))

# Pad sequences
def pad_embeddings(embeddings, max_len):
    return pad_sequence([torch.nn.functional.pad(e, (0, 0, 0, max_len - e.shape[0])) for e in embeddings], batch_first=True, padding_value=0.0)

padded_epi = pad_embeddings(epi_embeddings, max_len)
padded_tra = pad_embeddings(tra_embeddings, max_len)
padded_trb = pad_embeddings(trb_embeddings, max_len)

# Concatenate along sequence dimension
padded_combined = torch.cat([padded_tra, padded_trb, padded_epi], dim=1)

# Save padded embeddings
padd_paired_all_epi_path = '../../data/embeddings/paired/allele/padded_Epitope_paired_embeddings.npz'
padd_paired_all_tra_path = '../../data/embeddings/paired/allele/padded_TRA_paired_embeddings.npz'
padd_paired_all_trb_path = '../../data/embeddings/paired/allele/padded_TRB_paired_embeddings.npz'
padd_paired_combined_path = '../../data/embeddings/paired/allele/padded_Combined_paired_embeddings.npz'

np.savez(padd_paired_all_epi_path, **{key: padded_epi[i].numpy() for i, key in enumerate(epi_data)})
np.savez(padd_paired_all_tra_path, **{key: padded_tra[i].numpy() for i, key in enumerate(tra_data)})
np.savez(padd_paired_all_trb_path, **{key: padded_trb[i].numpy() for i, key in enumerate(trb_data)})
np.savez(padd_paired_combined_path, combined=padded_combined.numpy())

print("Padded and concatenated embeddings saved successfully.")


RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 41519 but got size 45261 for tensor number 1 in the list.

## beta and paired

In [6]:
import torch
torch.cuda.empty_cache()


In [3]:
import numpy as np
import torch
from torch.nn.utils.rnn import pad_sequence

# Check if GPU is available
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

# Paths to embeddings files
# paired_all_epi_path = '../../data/embeddings/paired/allele/Epitope_paired_embeddings.npz'
# paired_all_tra_path = '../../data/embeddings/paired/allele/TRA_paired_embeddings.npz'
# paired_all_trb_path = '../../data/embeddings/paired/allele/TRB_paired_embeddings.npz'

beta_all_epi_path = '../../data/embeddings/beta/allele/Epitope_beta_embeddings.npz'
beta_all_trb_path = '../../data/embeddings/beta/allele/TRB_beta_embeddings.npz'

# Load NPZ files into GPU
def load_embeddings_to_gpu(path):
    data = np.load(path, allow_pickle=True)
    return {key: torch.tensor(data[key], device=device) for key in data}

# epi_embeddings = load_embeddings_to_gpu(paired_all_epi_path)
# tra_embeddings = load_embeddings_to_gpu(paired_all_tra_path)
# trb_embeddings = load_embeddings_to_gpu(paired_all_trb_path)

beta_epi_embeddings = load_embeddings_to_gpu(beta_all_epi_path)
beta_trb_embeddings = load_embeddings_to_gpu(beta_all_trb_path)

# Find max sequence length
# max_len = max(max(e.shape[0] for e in epi_embeddings.values()), 
#               max(e.shape[0] for e in tra_embeddings.values()), 
#               max(e.shape[0] for e in trb_embeddings.values()))

beta_max_len = max(max(e.shape[0] for e in beta_epi_embeddings.values()), 
                    max(e.shape[0] for e in beta_trb_embeddings.values()))

# Function to pad embeddings on GPU
def pad_embeddings(embeddings, max_len):
    return pad_sequence(
        [torch.nn.functional.pad(e, (0, 0, 0, max_len - e.shape[0])) for e in embeddings.values()],
        batch_first=True, padding_value=0.0
    )

# Pad embeddings (all computations on GPU)
# padded_epi = pad_embeddings(epi_embeddings, max_len)
# padded_tra = pad_embeddings(tra_embeddings, max_len)
# padded_trb = pad_embeddings(trb_embeddings, max_len)

padded_beta_epi = pad_embeddings(beta_epi_embeddings, beta_max_len)
# padded_beta_trb = pad_embeddings(beta_trb_embeddings, beta_max_len)

# Move back to CPU before saving
# padded_epi = padded_epi.cpu().numpy()
# padded_tra = padded_tra.cpu().numpy()
# padded_trb = padded_trb.cpu().numpy()

padded_beta_epi = padded_beta_epi.cpu().numpy()
# padded_beta_trb = padded_beta_trb.cpu().numpy()

# Save padded embeddings
# padd_paired_all_epi_path = '../../data/embeddings/paired/allele/padded_Epitope_paired_embeddings.npz'
# padd_paired_all_tra_path = '../../data/embeddings/paired/allele/padded_TRA_paired_embeddings.npz'
# padd_paired_all_trb_path = '../../data/embeddings/paired/allele/padded_TRB_paired_embeddings.npz'

padd_beta_all_epi_path = '../../data/embeddings/beta/allele/padded_Epitope_beta_embeddings.npz'
# padd_beta_all_trb_path = '../../data/embeddings/beta/allele/padded_TRB_beta_embeddings.npz'

# np.savez(padd_paired_all_epi_path, **{key: padded_epi[i] for i, key in enumerate(epi_embeddings)})
# np.savez(padd_paired_all_tra_path, **{key: padded_tra[i] for i, key in enumerate(tra_embeddings)})
# np.savez(padd_paired_all_trb_path, **{key: padded_trb[i] for i, key in enumerate(trb_embeddings)})

np.savez(padd_beta_all_epi_path, **{key: padded_beta_epi[i] for i, key in enumerate(beta_epi_embeddings)})
# np.savez(padd_beta_all_trb_path, **{key: padded_beta_trb[i] for i, key in enumerate(beta_trb_embeddings)})

print("Padded embedding saved successfully.")


Using device: cuda


OutOfMemoryError: CUDA out of memory. Tried to allocate 2.00 MiB. GPU 0 has a total capacity of 14.56 GiB of which 2.75 MiB is free. Including non-PyTorch memory, this process has 14.56 GiB memory in use. Of the allocated memory 14.38 GiB is allocated by PyTorch, and 64.34 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

## Building the Model
## Step by Step

Step 0: Baseline Transformer Block \


In [8]:
import torch
import torch.nn as nn

class AttentionBlock(nn.Module):
    def __init__(self, embed_dim, num_heads, dropout=0.1):
        super(AttentionBlock, self).__init__()
        self.attn = nn.MultiheadAttention(embed_dim, num_heads, dropout=dropout)
        self.norm1 = nn.LayerNorm(embed_dim)  # Normalization for stability
        self.dropout = nn.Dropout(dropout)  # Dropout to prevent overfitting

    def forward(self, x):
        # Multihead Attention with Residual Connection
        attn_output, _ = self.attn(x, x, x)
        x = self.norm1(x + self.dropout(attn_output))  # Add & Norm
        
        return x


Step 1: Data Loading and Preprocessing

In [9]:
import pandas as pd
import numpy as np

# Load the training and validation data
train_path = '../../data/splitted_datasets/allele/beta/train.tsv'
validation_path = '../../data/splitted_datasets/allele/beta/validation.tsv'

train_data = pd.read_csv(train_path, sep='\t')
validation_data = pd.read_csv(validation_path, sep='\t')

# Load the embeddings
tcr_embeddings_path = '../../data/embeddings/beta/allele/TRB_beta_embeddings.npz'
epitope_embeddings_path = '../../data/embeddings/beta/allele/Epitope_beta_embeddings.npz'

tcr_embeddings = np.load(tcr_embeddings_path, allow_pickle=True)
epitope_embeddings = np.load(epitope_embeddings_path, allow_pickle=True)

/tmp/ipykernel_30452/2300908741.py:8: DtypeWarning: Columns (1,5) have mixed types. Specify dtype option on import or set low_memory=False.
  train_data = pd.read_csv(train_path, sep='\t')


Step 2: Padding the Embeddings

In [10]:
def pad_embeddings(embeddings_dict, max_length):
    padded_embeddings = {}
    for key, embedding in embeddings_dict.items():
        padded_embedding = np.zeros((max_length, embedding.shape[1]))
        padded_embedding[:embedding.shape[0], :] = embedding
        padded_embeddings[key] = padded_embedding
    return padded_embeddings

# Determine the maximum length for TCR and Epitope embeddings
max_tcr_length = max([embedding.shape[0] for embedding in tcr_embeddings.values()])
max_epitope_length = max([embedding.shape[0] for embedding in epitope_embeddings.values()])

# Pad the embeddings
padded_tcr_embeddings = pad_embeddings(tcr_embeddings, max_tcr_length)
padded_epitope_embeddings = pad_embeddings(epitope_embeddings, max_epitope_length)

In [ ]:
#  TCR_name         TRBV        TRBJ            TRB_CDR3 TRBC    Epitope  \
# 0      257  TRBV20-1*01  TRBJ2-5*01  CSARIWPYPAGGEETQYF  NaN  KLGGALQAK   
# 1      358    TRBV28*01  TRBJ2-1*01     CASSKGLAGLDEQFF  NaN   RAKFKQLL   
# 2      382   TRBV6-6*01  TRBJ2-5*01     CATQTPDSRRETQYF  NaN  KLGGALQAK   
# 3      393  TRBV20-1*01  TRBJ1-2*01     CSARDLDSLTNGYTF  NaN  KLGGALQAK   
# 4      396  TRBV10-2*01  TRBJ2-7*01       CASSEDREDEQYF  NaN  KLGGALQAK   

#            MHC  Binding  task  
# 0  HLA-A*03:01        1   NaN  
# 1  HLA-B*08:01        1   NaN  
# 2  HLA-A*03:01        1   NaN  
# 3  HLA-A*03:01        1   NaN  
# 4  HLA-A*03:01        1   NaN  
# Train dataset length: 319226

Step 3: Creating the Dataset and DataLoader

In [11]:
from torch.utils.data import Dataset, DataLoader

class TCR_Epitope_Dataset(Dataset):
    def __init__(self, data, tcr_embeddings, epitope_embeddings):
        self.data = data
        self.tcr_embeddings = tcr_embeddings
        self.epitope_embeddings = epitope_embeddings

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        row = self.data.iloc[idx]
        tcr_key = row['TRB_CDR3']
        epitope_key = row['Epitope']
        label = row['Binding']
        
        tcr_embedding = self.tcr_embeddings[tcr_key]
        epitope_embedding = self.epitope_embeddings[epitope_key]
        
        return tcr_embedding, epitope_embedding, label

# Create the datasets
train_dataset = TCR_Epitope_Dataset(train_data, padded_tcr_embeddings, padded_epitope_embeddings)
validation_dataset = TCR_Epitope_Dataset(validation_data, padded_tcr_embeddings, padded_epitope_embeddings)

# Create the dataloaders
batch_size = 32
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
validation_loader = DataLoader(validation_dataset, batch_size=batch_size, shuffle=False)

Step 4: Building the Model

In [12]:
class TCR_Epitope_Transformer(nn.Module):
    def __init__(self, embed_dim, num_heads, num_layers, max_tcr_length, max_epitope_length, dropout=0.1):
        super(TCR_Epitope_Transformer, self).__init__()
        
        # TCR and Epitope embedding layers
        self.tcr_embedding = nn.Linear(1024, embed_dim)
        self.epitope_embedding = nn.Linear(1024, embed_dim)
        
        # Positional Encoding
        self.tcr_positional_encoding = nn.Parameter(torch.zeros(1, max_tcr_length, embed_dim))
        self.epitope_positional_encoding = nn.Parameter(torch.zeros(1, max_epitope_length, embed_dim))
        
        # Transformer layers
        self.transformer_layers = nn.ModuleList([
            AttentionBlock(embed_dim, num_heads, dropout) for _ in range(num_layers)
        ])
        
        # Output layer
        self.output_layer = nn.Linear(embed_dim, 1)
        
    def forward(self, tcr, epitope):
        # Embed TCR and Epitope
        tcr = self.tcr_embedding(tcr) + self.tcr_positional_encoding
        epitope = self.epitope_embedding(epitope) + self.epitope_positional_encoding
        
        # Concatenate TCR and Epitope embeddings
        combined = torch.cat((tcr, epitope), dim=1)
        
        # Pass through transformer layers
        for layer in self.transformer_layers:
            combined = layer(combined)
        
        # Global Average Pooling
        pooled = combined.mean(dim=1)
        
        # Output layer
        output = self.output_layer(pooled)
        
        return output

# Initialize the model
embed_dim = 128
num_heads = 8
num_layers = 4
model = TCR_Epitope_Transformer(embed_dim, num_heads, num_layers, max_tcr_length, max_epitope_length)

Step 5: Training the Model

In [13]:
import torch.optim as optim

# Loss function and optimizer
criterion = nn.BCEWithLogitsLoss()
optimizer = optim.Adam(model.parameters(), lr=1e-4)

# Training loop
num_epochs = 2 # 10
for epoch in range(num_epochs):
    model.train()
    for tcr, epitope, labels in train_loader:
        optimizer.zero_grad()
        
        # Forward pass
        outputs = model(tcr, epitope)
        loss = criterion(outputs.squeeze(), labels.float())
        
        # Backward pass and optimization
        loss.backward()
        optimizer.step()
    
    print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}')

RuntimeError: mat1 and mat2 must have the same dtype, but got Double and Float

Step 6: Validation

In [ ]:
model.eval()
with torch.no_grad():
    correct = 0
    total = 0
    for tcr, epitope, labels in validation_loader:
        outputs = model(tcr, epitope)
        predicted = torch.sigmoid(outputs) > 0.5
        total += labels.size(0)
        correct += (predicted.squeeze() == labels).sum().item()
    
    accuracy = 100 * correct / total
    print(f'Validation Accuracy: {accuracy:.2f}%')

Step 7: Checking if Things are Working Properly

In [ ]:
# Example check for shapes
for tcr, epitope, labels in train_loader:
    print(f'TCR shape: {tcr.shape}')
    print(f'Epitope shape: {epitope.shape}')
    print(f'Labels shape: {labels.shape}')
    break

In [ ]:
import torch
import torch.nn as nn

import numpy as np

from torch.utils.data import Dataset, DataLoader, random_split


class TransformerBlock(nn.Module):
    def __init__(self, embed_dim, n_heads, dropout=0.1):
        """
        Args:
            embed_dim: Dimensionality of the input embeddings.
            n_heads: Number of attention heads.
            dropout: Dropout rate for regularization.
        """
        super(TransformerBlock, self).__init__()
        
        # Multihead Attention
        self.multihead_attn = nn.MultiheadAttention(embed_dim, n_heads, dropout=dropout)
        
        # Layer Normalization
        self.norm1 = nn.LayerNorm(embed_dim)
        self.norm2 = nn.LayerNorm(embed_dim)
        
        # Feedforward Network
        self.ffn = nn.Sequential(
            nn.Linear(embed_dim, 4 * embed_dim),  # Expand dimension
            nn.ReLU(),
            nn.Linear(4 * embed_dim, embed_dim)   # Compress back to original dimension
        )
        
        # Dropout
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        """
        Args:
            x: Input tensor of shape (seq_len, batch_size, embed_dim).
        
        Returns:
            Output tensor of shape (seq_len, batch_size, embed_dim).
        """
        # Multihead Attention
        attn_output, _ = self.multihead_attn(x, x, x)  # Self-attention
        x = x + self.dropout(attn_output)              # Residual connection
        x = self.norm1(x)                              # Layer normalization
        
        # Feedforward Network
        ffn_output = self.ffn(x)
        x = x + self.dropout(ffn_output)               # Residual connection
        x = self.norm2(x)                              # Layer normalization
        
        return x

Step 4: Testing the Updated Dataset\
Let's test the updated dataset to ensure the combined embeddings are in the correct shape:

In [5]:

# Load the .npz files
tcr_data = np.load('/home/ubuntu/data/embeddings/beta/gene/TCRPeg_tcr_embeddings.npz')
epitope_data = np.load('/home/ubuntu/data/embeddings/beta/gene/TCRPeg_Epitope_embeddings.npz')

# Print the keys in each file
print("Keys in TCR embeddings file:", list(tcr_data.keys()))
print("Keys in Epitope embeddings file:", list(epitope_data.keys()))

Keys in TCR embeddings file: ['embeddings', 'labels']
Keys in Epitope embeddings file: ['embeddings']


CHECK!!  
\
Step 1: Verify the Size of the Dataset

In [6]:
# Load the TCR and epitope embeddings
tcr_data = np.load('/home/ubuntu/data/embeddings/beta/gene/TCRPeg_tcr_embeddings.npz')
epitope_data = np.load('/home/ubuntu/data/embeddings/beta/gene/TCRPeg_Epitope_embeddings.npz')

tcr_embeddings = tcr_data['embeddings']  # Use the correct key
epitope_embeddings = epitope_data['embeddings']  # Use the correct key

print(f"Number of TCR embeddings: {len(tcr_embeddings)}")
print(f"Number of epitope embeddings: {len(epitope_embeddings)}")

Number of TCR embeddings: 570500
Number of epitope embeddings: 570500


Step 2: Ensure Labels Match the Dataset Size\
If you have labels, ensure the labels array has the same length as the number of TCR/epitope embeddings. If you don't have labels, we can create dummy labels.

In [7]:
# If you have labels, load them here
path_to_labels = '/home/ubuntu/data/embeddings/beta/gene/TCRPeg_tcr_embeddings.npz'
labels_data = np.load(path_to_labels)  # Example: Load labels from a file
labels = labels_data['labels']

# If you don't have labels, create dummy labels
# labels = np.zeros(len(tcr_embeddings))  # Dummy labels (all zeros)

print(f"Number of labels: {len(labels)}")

Number of labels: 570500


Split the dataset into training, validation and test\
This is only a dummy splitting, since for real testing we'll use 
a separate test dataset.

In [ ]:
# Split the dataset into training and validation sets
train_size = int(0.8 * len(dataset))  # 80% training
val_size = len(dataset) - train_size   # 20% validation
train_dataset, val_dataset = random_split(dataset, [train_size, val_size])


Step 3: Update the Dataset Class \
Update the TCR_Epitope_Dataset class to ensure it uses the correct indices and handles the dataset size properly.

In [10]:
class TCR_Epitope_Dataset(Dataset):
    def __init__(self, tcr_embeddings, epitope_embeddings, labels=None):
        """
        Args:
            tcr_embeddings: Array of TCR embeddings.
            epitope_embeddings: Array of epitope embeddings.
            labels: Optional array of labels (1 for binding, 0 for non-binding).
        """
        self.tcr_embeddings = tcr_embeddings
        self.epitope_embeddings = epitope_embeddings
        
        # Ensure the number of TCR and epitope embeddings match
        assert len(self.tcr_embeddings) == len(self.epitope_embeddings), \
            "Number of TCR and epitope embeddings must match!"
        
        # If labels are provided, use them; otherwise, create dummy labels
        self.labels = labels if labels is not None else np.zeros(len(self.tcr_embeddings))
        
    def __len__(self):
        return len(self.tcr_embeddings)
    
    def __getitem__(self, idx):
        """
        Returns:
            combined_embedding: Combined TCR and epitope embeddings of shape (2, 1024).
            label: Binding label (1 or 0).
        """
        tcr_embedding = self.tcr_embeddings[idx]
        epitope_embedding = self.epitope_embeddings[idx]
        label = self.labels[idx]
        
        # Convert to PyTorch tensors
        tcr_embedding = torch.tensor(tcr_embedding, dtype=torch.float32)
        epitope_embedding = torch.tensor(epitope_embedding, dtype=torch.float32)
        label = torch.tensor(label, dtype=torch.float32)
        
        # Combine TCR and epitope embeddings along the sequence dimension
        combined_embedding = torch.stack([tcr_embedding, epitope_embedding], dim=0)  # Shape: (2, 1024)
        
        return combined_embedding, label

Step 4: Create the Dataset and DataLoader \
Now, create the dataset and DataLoader with the correct data:

In [11]:
# Create the dataset
dataset = TCR_Epitope_Dataset(tcr_embeddings, epitope_embeddings, labels)

# Inspect the dataset
print(f"Number of samples: {len(dataset)}")
combined_embedding, label = dataset[0]  # Get the first sample
print(f"Combined embedding shape: {combined_embedding.shape}")  # Should be (2, 1024)
print(f"Label: {label}")

# Create a DataLoader
batch_size = 32
dataloader = DataLoader(dataset, batch_size=batch_size, shuffle=True)

# Iterate through the DataLoader
for batch in dataloader:
    combined_embeddings, labels = batch
    print(f"Combined embeddings batch shape: {combined_embeddings.shape}")  # Should be (batch_size, 2, 1024)
    print(f"Labels batch shape: {labels.shape}")  # Should be (batch_size,)
    break  # Stop after the first batch for inspection

Number of samples: 570500
Combined embedding shape: torch.Size([2, 1024])
Label: 1.0
Combined embeddings batch shape: torch.Size([32, 2, 1024])
Labels batch shape: torch.Size([32])


Step 5: Integrate the Transformer Block\
We'll create a model class that:

Takes the combined TCR and epitope embeddings as input.

Passes them through the TransformerBlock.

Flattens the output and passes it through a classifier.

In [12]:


class TCR_Epitope_Model(nn.Module):
    def __init__(self, embed_dim, n_heads, dropout=0.1, classifier_hidden_dim=64):
        """
        Args:
            embed_dim: Dimensionality of the input embeddings (1024 in your case).
            n_heads: Number of attention heads in the transformer.
            dropout: Dropout rate for regularization.
            classifier_hidden_dim: Hidden dimension of the classifier.
        """
        super(TCR_Epitope_Model, self).__init__()
        
        # Transformer Block
        self.transformer_block = TransformerBlock(embed_dim, n_heads, dropout)
        
        # Classifier
        self.classifier = nn.Sequential(
            nn.Linear(2 * embed_dim, classifier_hidden_dim),  # Input: flattened transformer output
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(classifier_hidden_dim, 1)  # Output: binary prediction
        )
    
    def forward(self, x):
        """
        Args:
            x: Input tensor of shape (batch_size, 2, embed_dim).
        
        Returns:
            logits: Output tensor of shape (batch_size, 1).
        """
        # Permute input to (seq_len, batch_size, embed_dim) for the transformer
        x = x.permute(1, 0, 2)  # Shape: (2, batch_size, embed_dim)
        
        # Pass through the transformer block
        x = self.transformer_block(x)  # Shape: (2, batch_size, embed_dim)
        
        # Permute back to (batch_size, seq_len, embed_dim)
        x = x.permute(1, 0, 2)  # Shape: (batch_size, 2, embed_dim)
        
        # Flatten the output
        x = x.reshape(x.size(0), -1)  # Shape: (batch_size, 2 * embed_dim)
        
        # Pass through the classifier
        logits = self.classifier(x)  # Shape: (batch_size, 1)
        
        return logits

Step 6: Test the Model \
Let's test the model with a batch of data to ensure everything works:

In [ ]:
# # Initialize the model
# embed_dim = 1024  # Dimensionality of TCR and epitope embeddings
# n_heads = 4       # Number of attention heads
# model = TCR_Epitope_Model(embed_dim, n_heads)

# # Get a batch of data from the DataLoader
# for batch in dataloader:
#     combined_embeddings, labels = batch
#     break  # Stop after the first batch

# # Pass the batch through the model
# logits = model(combined_embeddings)
# print(f"Logits shape: {logits.shape}")  # Should be (batch_size, 1)

Logits shape: torch.Size([32, 1])


we forgot to use GPU. Then...

In [22]:
import torch

# Check if GPU is available
if torch.cuda.is_available():
    device = torch.device("cuda")
    print(f"GPU is available: {torch.cuda.get_device_name(0)}")
else:
    device = torch.device("cpu")
    print("GPU is not available. Using CPU.")

# Move the model to the GPU (if available)
model = model.to(device)

# Move Data to GPU

for batch in dataloader:
    combined_embeddings, labels = batch
    
    # Move data to the GPU (if available)
    combined_embeddings = combined_embeddings.to(device)
    labels = labels.to(device)
    
    # Rest of the training loop...

# Verify GPU Usage

# Check model device
print(f"Model is on: {next(model.parameters()).device}")

# Check data device
print(f"Data is on: {combined_embeddings.device}")

GPU is available: Tesla T4
Model is on: cuda:0
Data is on: cuda:0


Step 7: Add a Training Loop\
Now, let's add a simple training loop to train the model. We'll use binary cross-entropy loss and the Adam optimizer.

In [23]:
import torch.optim as optim

# Initialize the model, loss function, and optimizer
model = TCR_Epitope_Model(embed_dim, n_heads).to(device)  # Move model to GPU
criterion = nn.BCEWithLogitsLoss()  # Binary cross-entropy loss with logits
optimizer = optim.Adam(model.parameters(), lr=1e-3)

# Training loop
num_epochs = 5
for epoch in range(num_epochs):
    model.train()  # Set the model to training mode
    epoch_loss = 0.0
    
    for batch in dataloader:
        combined_embeddings, labels = batch
        
        # Move data to the GPU (if available)
        combined_embeddings = combined_embeddings.to(device)
        labels = labels.to(device)
        
        # Zero the gradients
        optimizer.zero_grad()
        
        # Forward pass
        logits = model(combined_embeddings).squeeze()  # Shape: (batch_size,)
        
        # Compute loss
        loss = criterion(logits, labels)
        
        # Backward pass and optimization
        loss.backward()
        optimizer.step()
        
        # Accumulate loss
        epoch_loss += loss.item()
    
    # Print epoch loss
    print(f"Epoch {epoch + 1}/{num_epochs}, Loss: {epoch_loss / len(dataloader)}")

Epoch 1/5, Loss: 0.30530472857386276
Epoch 2/5, Loss: 0.1719683983865046
Epoch 3/5, Loss: 0.157329112976129
Epoch 4/5, Loss: 0.14955465956043631
Epoch 5/5, Loss: 0.14537664496026595


Step 1: Prepare a Validation Set\

In [ ]:


# Split the dataset into training and validation sets
train_size = int(0.8 * len(dataset))  # 80% training
val_size = len(dataset) - train_size   # 20% validation
train_dataset, val_dataset = random_split(dataset, [train_size, val_size])

# Create DataLoaders for training and validation
train_dataloader = DataLoader(train_dataset, batch_size=32, shuffle=True)
val_dataloader = DataLoader(val_dataset, batch_size=32, shuffle=False)


Step 2: Evaluation Function\
We'll write a function to evaluate the model on the validation set. This function will:

Switch the model to evaluation mode.

Disable gradient computation.

Compute predictions and metrics like accuracy, ROC-AUC, and precision-recall.

In [ ]:
from sklearn.metrics import accuracy_score, roc_auc_score, precision_score, recall_score

def evaluate(model, dataloader, device):
    model.eval()  # Set the model to evaluation mode
    all_labels = []
    all_predictions = []
    
    with torch.no_grad():  # Disable gradient computation
        for batch in dataloader:
            combined_embeddings, labels = batch
            
            # Move data to the GPU (if available)
            combined_embeddings = combined_embeddings.to(device)
            labels = labels.to(device)
            
            # Forward pass
            logits = model(combined_embeddings).squeeze()
            predictions = torch.sigmoid(logits)  # Convert logits to probabilities
            
            # Store predictions and labels
            all_labels.extend(labels.cpu().numpy())
            all_predictions.extend(predictions.cpu().numpy())
    
    # Convert lists to numpy arrays
    all_labels = np.array(all_labels)
    all_predictions = np.array(all_predictions)
    
    # Compute metrics
    accuracy = accuracy_score(all_labels, all_predictions > 0.5)  # Threshold at 0.5
    roc_auc = roc_auc_score(all_labels, all_predictions)
    precision = precision_score(all_labels, all_predictions > 0.5, zero_division=0)
    recall = recall_score(all_labels, all_predictions > 0.5, zero_division=0)
    
    return accuracy, roc_auc, precision, recall

Step 3: Evaluate the Model

In [ ]:
num_epochs = 5
for epoch in range(num_epochs):
    model.train()  # Set the model to training mode
    epoch_loss = 0.0
    
    # Training loop
    for batch in train_dataloader:
        combined_embeddings, labels = batch
        
        # Move data to the GPU (if available)
        combined_embeddings = combined_embeddings.to(device)
        labels = labels.to(device)
        
        # Zero the gradients
        optimizer.zero_grad()
        
        # Forward pass
        logits = model(combined_embeddings).squeeze()
        
        # Compute loss
        loss = criterion(logits, labels)
        
        # Backward pass and optimization
        loss.backward()
        optimizer.step()
        
        # Accumulate loss
        epoch_loss += loss.item()
    
    # Print training loss
    print(f"Epoch {epoch + 1}/{num_epochs}, Loss: {epoch_loss / len(train_dataloader)}")
    
    # Evaluate on the validation set
    accuracy, roc_auc, precision, recall = evaluate(model, val_dataloader, device)
    print(f"Validation Metrics - Accuracy: {accuracy:.4f}, ROC-AUC: {roc_auc:.4f}, Precision: {precision:.4f}, Recall: {recall:.4f}")

Step 4: Save the Model

In [ ]:
# Save the model
torch.save(model.state_dict(), "tcr_epitope_model.pth")

# To load the model later:

# Load the model
model = TCR_Epitope_Model(embed_dim, n_heads).to(device)
model.load_state_dict(torch.load("tcr_epitope_model.pth"))

Let's proceed with hyperparameter tuning, test set evaluation, and visualizations for your Multihead Attention Model. We'll break this down into clear steps. 

Step 1: Hyperparameter Tuning \
Hyperparameter tuning involves finding the best set of hyperparameters (e.g., learning rate, number of attention heads, dropout rate) for your model. We'll use a simple grid search approach.

Key Hyperparameters to Tune:

Learning Rate: Controls the step size during optimization.

Number of Attention Heads: Determines how many parallel attention mechanisms to use.

Dropout Rate: Regularization to prevent overfitting.

Hidden Dimension of the Classifier: Size of the hidden layer in the classifier.

In [ ]:
from itertools import product

# Define hyperparameter grid
learning_rates = [1e-3, 1e-4]
n_heads_list = [2, 4, 8]
dropout_rates = [0.1, 0.2]
classifier_hidden_dims = [64, 128]

# Iterate over all combinations
best_roc_auc = 0
best_hyperparams = {}

for lr, n_heads, dropout, hidden_dim in product(learning_rates, n_heads_list, dropout_rates, classifier_hidden_dims):
    print(f"Testing: lr={lr}, n_heads={n_heads}, dropout={dropout}, hidden_dim={hidden_dim}")
    
    # Initialize model with current hyperparameters
    model = TCR_Epitope_Model(embed_dim=1024, n_heads=n_heads, dropout=dropout, classifier_hidden_dim=hidden_dim).to(device)
    optimizer = optim.Adam(model.parameters(), lr=lr)
    criterion = nn.BCEWithLogitsLoss()
    
    # Train the model
    for epoch in range(5):  # Short training for hyperparameter tuning
        model.train()
        for batch in train_dataloader:
            combined_embeddings, labels = batch
            combined_embeddings, labels = combined_embeddings.to(device), labels.to(device)
            
            optimizer.zero_grad()
            logits = model(combined_embeddings).squeeze()
            loss = criterion(logits, labels)
            loss.backward()
            optimizer.step()
    
    # Evaluate on the validation set
    accuracy, roc_auc, precision, recall = evaluate(model, val_dataloader, device)
    print(f"Validation Metrics - Accuracy: {accuracy:.4f}, ROC-AUC: {roc_auc:.4f}, Precision: {precision:.4f}, Recall: {recall:.4f}")
    
    # Track the best hyperparameters
    if roc_auc > best_roc_auc:
        best_roc_auc = roc_auc
        best_hyperparams = {
            "learning_rate": lr,
            "n_heads": n_heads,
            "dropout": dropout,
            "classifier_hidden_dim": hidden_dim
        }

print(f"Best Hyperparameters: {best_hyperparams}, Best ROC-AUC: {best_roc_auc:.4f}")

Step 2: Test Set Evaluation \
Once you've identified the best hyperparameters, evaluate the model on the test set.

Load the Test Set:

In [ ]:
# Load test embeddings (assuming Scenario B: shared embeddings)
test_tcr_embeddings = all_tcr_embeddings[test_tcr_indices]
test_epitope_embeddings = all_epitope_embeddings[test_epitope_indices]

# Create test dataset and DataLoader
test_dataset = TCR_Epitope_Dataset(test_tcr_embeddings, test_epitope_embeddings, test_labels)
test_dataloader = DataLoader(test_dataset, batch_size=32, shuffle=False)

Evaluate on the Test Set:

In [ ]:
# Initialize the model with the best hyperparameters
best_model = TCR_Epitope_Model(
    embed_dim=1024,
    n_heads=best_hyperparams["n_heads"],
    dropout=best_hyperparams["dropout"],
    classifier_hidden_dim=best_hyperparams["classifier_hidden_dim"]
).to(device)

# Load the trained weights (if you saved the model)
best_model.load_state_dict(torch.load("best_model.pth"))

# Evaluate on the test set
test_accuracy, test_roc_auc, test_precision, test_recall = evaluate(best_model, test_dataloader, device)
print(f"Test Metrics - Accuracy: {test_accuracy:.4f}, ROC-AUC: {test_roc_auc:.4f}, Precision: {test_precision:.4f}, Recall: {test_recall:.4f}")

Step 3: Visualizations \
Visualizations help you understand the model's performance. We'll create:

ROC Curve: To visualize the trade-off between true positive rate (TPR) and false positive rate (FPR).

Precision-Recall Curve: To visualize the trade-off between precision and recall.

Confusion Matrix: To show the distribution of predictions.

ROC Curve:


In [ ]:
from sklearn.metrics import roc_curve, auc
import matplotlib.pyplot as plt

# Get predictions and labels
all_labels = []
all_predictions = []

best_model.eval()
with torch.no_grad():
    for batch in test_dataloader:
        combined_embeddings, labels = batch
        combined_embeddings, labels = combined_embeddings.to(device), labels.to(device)
        
        logits = best_model(combined_embeddings).squeeze()
        predictions = torch.sigmoid(logits)
        
        all_labels.extend(labels.cpu().numpy())
        all_predictions.extend(predictions.cpu().numpy())

# Compute ROC curve
fpr, tpr, thresholds = roc_curve(all_labels, all_predictions)
roc_auc = auc(fpr, tpr)

# Plot ROC curve
plt.figure()
plt.plot(fpr, tpr, color='darkorange', lw=2, label=f'ROC curve (area = {roc_auc:.2f})')
plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver Operating Characteristic (ROC) Curve')
plt.legend(loc="lower right")
plt.show()

In [ ]:
from sklearn.metrics import precision_recall_curve

# Compute precision-recall curve
precision, recall, _ = precision_recall_curve(all_labels, all_predictions)

# Plot precision-recall curve
plt.figure()
plt.plot(recall, precision, color='blue', lw=2, label='Precision-Recall curve')
plt.xlabel('Recall')
plt.ylabel('Precision')
plt.title('Precision-Recall Curve')
plt.legend(loc="lower left")
plt.show()

In [ ]:
from sklearn.metrics import confusion_matrix
import seaborn as sns

# Compute confusion matrix
binary_predictions = (np.array(all_predictions) > 0.5).astype(int)
cm = confusion_matrix(all_labels, binary_predictions)

# Plot confusion matrix
plt.figure()
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=['Not Binding', 'Binding'], yticklabels=['Not Binding', 'Binding'])
plt.xlabel('Predicted')
plt.ylabel('True')
plt.title('Confusion Matrix')
plt.show()